
const cardTextContent = {
  "btninfo_art": {
    ar:"بيان الفنان",
    en:"Artist Statement"
  },
  "btninfo_detail": {
    ar:"تفاصيل العمل الفني",
    en:"Artwork Details"
  },
  "work-01": {
    artist: {
      ar: "بيان الفنان حول هذه اللوحةأُبدع هذا العمل الفني انعكاسًا لتاريخ إيران العريق والحوار الأبدي بين النور والظلام.يمثل النصف الذهبي بريق الحضارة - المجد الثقافي والحكمة والإيمان لشعب نهض عبر العصور.يحمل النصف المظلم وطأة المشقة والكفاح - أزمنة الحرب والفقد والبعث. معًا، يرويان قصة أمة سقطت ثم نهضت من جديد، في كل مرة أقوى وأكثر إشراقًا.الأشكال الخطية ليست مجرد كلمات؛ إنها حركات روحية - رقصة بصرية بين الماضي والحاضر، حيث حتى الصمت له معنى.من خلال تناغم الذهبي والأسود، أهدف إلى إظهار أن التباين يُضفي الحياة على الجمال: لا معنى للضوء بدون ظل، والعظمة تولد من خلال الصمود.تعبر هذه اللوحة عن إيماني بالصلة العميقة بين الجمال والإيمان والهوية الإيرانية.كل منحنى وخط يعكس الروح الشعرية والمرنة لهذه الأرض - وهو المكان الذي وجد طريقه دائمًا بين ذهب الأمل وظلام التجربة.",
      en: "Artist’s Statement about this Painting(A Spell from the Heart of Ancient Persia)From the silent dust of centuries, a divine pulse awakens — a whisper rising from the golden heart of Persia, carrying the breath of forgotten kings and the fire of eternal light. This painting is not merely seen; it summons. It draws you into its spell until you feel time folding within your chest, until the rhythm of your heartbeat echoes the voice of the ancients.The Faravahar, crowned in turquoise and gold, hovers at the center like a guardian between worlds — half human, half light — reminding us that the soul was never meant to crawl, but to soar. Around it, the sacred vines of creation twist and bloom, shimmering like prayers caught in midair. Each curve, each burst of color, is alive — breathing, watching, whispering the language of eternity.This artwork is not a tribute; it is a resurrection.It revives the myth, the wisdom, and the burning elegance of a civilization that refused to fade.It speaks to the seeker, to the dreamer, to the one who still believes that art can awaken what history tried to silence.Let it not hang on your wall — let it enter you.Let its wings stir the dust of your soul."
    },
    details: {
      ar: "المقاس: ٣٠×٤٠ سم النمط: مستوحى من الشعر والفن الفارسي التقنية: باتينا تقنية الرسم: ألوان أكريليك (مطلية يدويًا)المادة الأساسية: لوح خشبي ٣ مم📏 تتوفر مقاسات مخصصة عند الطلبالمواد: ألوان أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿✨ المميزات:طبقة واقية من الهواء والعوامل الطبيعيةتغليف آمن لتوصيل آمنمناسب للديكور المنزلي والمكاتب والمساحات الفنية",
      en: "Size: 30×40 cmStyle: Inspired by Persian poetry and artTechnique Style: PatinaPainting Technique: Acrylic colors (hand-finished)Base Material: 3 mm wooden panel📏 Custom sizes available upon requestMaterials: Eco-friendly, renewable acrylic colors and natural compounds 🌿✨ Features:Protective coating against air and natural effectsSecure packaging for safe deliverySuitable for home décor, offices, and artistic spaces"
    }
  },
  "work-02": {
    artist: { 
      ar: "تصريح الفنان عن هذه اللوحة الجدران المقدسة، ويعود الآن في شكل جديد. كل حرف يستقر كحجر مقدس، يبني عالماً صامتاً يتحدث من خلال السكون.يتوهج السطح الذهبي للوحة كضوء ينبثق من الظلام - ليس بريقاً سطحياً، بل دفءً عميقاً، رمزاً هادئاً للخلود. على خلفية سوداء خشنة، يظهر هذا الإشراق الذهبي كأثر أمل ينجو من التآكل. كل طبقة باهتة، كل زاوية مهترئة، وكل علامة مكسورة تروي قصة مرور الزمن - كجدار قديم همس بالدعاء لقرون.هذه الخطوط الكوفية ليست للقراءة، بل للشعور بها. يكمن معناها في الفراغ بين الحروف - في الصمت الذي يدعو للتأمل. ينجرف المشاهد بين النظام والفوضى، باحثاً عن الحقيقة الخفية. فهو يذكرنا بأن الجمال لا يكمن دائمًا في الوضوح، بل في كثير من الأحيان في الغموض الذي يجعلنا نتوقف ونفكر.تحت السطح، ينكشف حوار هادئ بين الزمن والأبدية. يبدو الماضي وكأنه ينبع من تحت طبقات الطلاء، نابضًا بالحياة كلما لامسته أشعة الشمس. هذا العمل الفني ليس مجرد تركيبة بصرية من الحروف، بل هو ذاكرة حية، انعكاس للإيمان والصمود، يُذكرنا بأن حتى ما يبدو قديمًا لا يزال يحمل في طياته بريقًا من الخلود.", 
      en: "Artist’s Statement about this PaintingIn this artwork, words are no longer mere carriers of meaning — they have become the essence of emotion itself. The Kufic script here stands like an architecture of spirit and time, a structure that once adorned sacred walls and now returns in a new form. Every letter rests like a sacred stone, building a silent world that speaks through stillness.The golden surface of the painting glows like light emerging from darkness — not a superficial shine, but a deep warmth, a quiet symbol of eternity. Against the rough black background, this golden radiance appears as a trace of hope surviving through decay. Each faded layer, each worn corner, and each broken mark tells the story of time passing — like an old wall that has whispered prayers for centuries.These Kufic lines are not meant to be read; they are meant to be felt. Their meaning lies in the space between letters — in the silence that invites reflection. The viewer drifts between order and chaos, searching for hidden truth. It reminds us that beauty does not always lie in clarity, but often in the mystery that makes us pause and think.Beneath the surface, a quiet dialogue unfolds between time and eternity. The past seems to rise from beneath the layers of paint, alive again each time light touches it. This artwork is not just a visual composition of letters — it is a living memory, a reflection of faith and endurance, reminding us that even what seems old still holds a spark of timelessness within." 
    },
    details: {
       ar: "المقاس: ٥٠×٧٠ سم النمط: مستوحى من الخط الكوفي التقنية: باتينا تقنية الرسم: ألوان أكريليك (صناعة يدوية المادة الأساسية: لوح خشبي ٦ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: ألوان أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 50×70 cm Style: Inspired by Kufic calligraphy Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 6 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces" 
      }
  },
  "work-03": {
    artist: { 
      ar: "بيان الفنان حول هذه اللوحة هذه اللوحة قصة ميلاد واستمرارية - رحلة من الأرض إلى الذهب، من الصمت إلى اليقظة. سطحها الأخضر ليس مجرد لون؛ إنه صدى لبداية الحياة، همس الخلق المنبعث من السكون. القوام غير المنتظم والعلامات القديمة هي ندوب الزمن الهادئة - آثار الصمود والتحول ومرور الوجود نفسه. في قلبها، يتنفس نقش البيزلي كشعلة حية، ملتفة من تربة الذاكرة. لا انحناءة ولا خط يأتيان عرضيًا. كل التواء يحمل إيقاع قرون - نبض ثقافة عريقة عرفت المجد والحزن. هنا، البيزلي ليس مجرد زينة؛ إنه روح تسعى للهروب من التكرار، لتندمج في ذاتها وتولد من جديد. إنه بذرة ونار في آن واحد - تواضع الأرض وعظمة النور متشابكان. يبرز الإطار الهندسي كجدران معبد صامتة، حاملاً في داخله رقصة الأشكال العضوية الجامحة. هذا التناقض بين النظام والحرية يعكس الحياة نفسها - التوازن بين ما يربطنا وما يسمح لنا بالنمو. من أعماق الخضرة العتيقة، ينبثق ضوء ذهبي، كشمس خفية تتسلل عبر أوراق غابة منسية. تحت طبقات الزمن، لا يزال شيء حيّاً - شيء توارثته الأجيال: الإيمان، والهوية، والتفاني للجمال. يحمل هذا العمل الفني همس روح أمة. النقشة - العريقة، الصامدة، الخالدة - تتأرجح عبر الزمن لكنها لا تنكسر أبدًا. خضرتها تنبض بالحياة والتجدد، وذهبها ينبض بالتألق الخالد. إن النظر إلى هذه اللوحة هو استحضار للذاكرة - حيث يتنفس التاريخ ألوانًا، ويحمل الصمت عاطفة. كل ضربة فرشاة هي تأمل، وخطوة تتجاوز السطح إلى الغيب. في سكونها، تتحدث اللوحة. تدعو المشاهد للتوقف، والتنفس، والإنصات - ففي مكان ما في هدوئها الأخضر والذهبي، لا يزال الجمال حيًا، ولن يتلاشى أبدًا.",
      en: "Artist’s Statement about this Painting This painting is a story of birth and continuity — a journey from earth to gold, from silence to awakening. Its green surface is not merely a color; it is the echo of life’s beginning, the whisper of creation rising from stillness. The irregular textures and aged marks are the quiet scars of time — traces of endurance, transformation, and the passage of existence itself. At its heart, the paisley motif breathes like a living flame, curling upward from the soil of memory. No curve or line is accidental. Every twist carries the rhythm of centuries — the pulse of an ancient culture that has known both glory and sorrow. Here, the paisley is not just decoration; it is a spirit seeking to escape repetition, to fold into itself and be reborn. It is both seed and fire — the humility of earth and the majesty of light intertwined. The geometric border stands like the calm walls of a silent temple, holding the wild dance of organic forms within. This contrast between order and freedom mirrors life itself — the balance between what binds us and what allows us to grow. From the depths of aged green, golden light emerges, like a hidden sun filtering through the leaves of a forgotten forest. Beneath the layers of time, something still lives — something passed from generation to generation: faith, identity, and a devotion to beauty. This artwork carries the whisper of a nation’s soul. The paisley — ancient, resilient, eternal — bends through time but never breaks. Its green speaks of life and renewal; its gold, of timeless brilliance. To look at this painting is to look into memory — where history breathes in color, and silence holds emotion. Every brushstroke is a meditation, a step beyond the surface into the unseen. In its stillness, the painting speaks. It invites the viewer to pause, to breathe, and to listen — for somewhere within its green and golden quiet, beauty still lives, and it will never fade." 
    },
    details: {
       ar: "المقاس: ٥٠×٧٠ سم النمط: مستوحى من زخارف الجدران الفارسية القديمة وأنماط البيزلي (بوتيه جغيه) التقنية: باتينا تقنية الطلاء: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٦ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 50×70 cm Style: Inspired by ancient Persian wall motifs and paisley patterns (Boteh Jegheh) Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 6 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-04": {
    artist: { 
      ar: "بيان الفنان حول هذه اللوحة في هذا العمل الفني، تتشابك الأنماط والحروف، كما لو أن الزمن نفسه قد ضل طريقه داخل هذه الدائرة المقدسة. في القلب تكمن مجموعة من الحروف الكوفية - أصداء من حضارة عريقة لا تزال تتنفس في أرواحنا. كل حرف هو جسد من النور والظل، وكل مسافة بينهما هي وقفة فكر وحضور. هذه الحروف لا تتكلم، لكنها مسموعة - صمتها يتردد صداه في الأبدية. تتفتّح الحدود كحديقة من التكرار والإيقاع. الأشكال الدوامة توازن بين السيطرة والحرية؛ درجات اللون الأحمر الترابي والفيروزي والزيتوني تُذكّر بجوهر التربة والسماء والدم - الثالوث الأبدي للروح الفارسية. وسط رقصة الأشكال هذه، ينبثق وهج ذهبي - ليس من المعدن، بل من جوهر المعنى نفسه. هذه القطعة ليست مجرد زينة - إنها رحلة نحو الهوية. كلما تأمل المشاهد، قلّت رؤيته وتعمق في إدراكه. الألوان والخطوط تجذب الذهن، طبقةً تلو الأخرى، حتى يصبح المشاهد جزءًا من اللوحة نفسها. هنا، لم يرسم الفنان بيده فحسب، بل بروحه أيضًا. كل ضربة فرشاة شهادة على إيمانه بالجمال والمعنى - جسر بين الهندسة المقدسة والفوضى الشعرية، بين المادة والروح. وأخيرًا، الصمت. الصمت بين الأشكال أبلغ من أصباغ الألوان نفسها. هذه اللوحة لا بداية لها ولا نهاية، إنها كدعاء، تدور بلا نهاية، تهمس بسر الخلود.",
      en: "Artist’s Statement about this Painting In this artwork, patterns and letters intertwine, as if time itself has lost its way within this sacred circle. At the heart lies a cluster of Kufic letters—echoes from an ancient civilization that still breathes within our souls. Each letter is a body of light and shadow, and every space between them is a pause of thought and presence. These letters do not speak, yet they are heard — their silence resounds with eternity. The borders bloom like a garden of repetition and rhythm. The swirling forms balance control and freedom; the earthy reds, turquoise, and olive tones recall the essence of soil, sky, and blood — the eternal triad of Persian spirit. Amid this dance of forms, a golden glow emerges — not from metal, but from the essence of meaning itself. This piece is not merely decorative — it is a journey into identity. The more the viewer gazes, the less they “see” and the more they enter. The colors and lines pull the mind inward, layer by layer, until the viewer becomes part of the painting itself. Here, the artist has painted not just with the hand, but with the soul. Each brushstroke is a testimony of faith in beauty and meaning — a bridge between sacred geometry and poetic chaos, between matter and spirit. And finally, silence. The silence left between the shapes speaks louder than the pigments themselves. This painting has neither beginning nor end — it is like a prayer, circling endlessly, whispering the secret of eternity." 
    },
    details: {
       ar: "المقاس: ٥٠×٧٠ سم النمط: مستوحى من زخارف الجدران القديمة وأنماط البايسل التقنية: باتينا تقنية الطلاء: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٦ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 50×70 cm Style: Inspired by ancient  wall motifs and paisley patterns  Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 6 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-05": {
    artist: { 
      ar: "تصريح الفنان عن هذه اللوحة تبدو هذه اللوحة كجلد الأرض - جريحًا، حيًا، وأبديًا. تشبه الخطوط المتشققة عروقًا عتيقة، تحمل ذكريات مدفونة تحت قرون من الصمت. ينبعث اللون الأخضر الداكن من همهمة هادئة، كغابة احترقت يومًا ما، لكنها لا تزال تتنفس تحت الرماد. قد تبدو من بعيد كجدار - قويًا، صلبًا - لكن كلما اقتربت، تُدرك أنها ليست جدارًا على الإطلاق. إنها جلد. جلد الأرض، جلد الروح، جلد إنسان قاوم الزمن نفسه. كل شق هو حد بين ما كان وما بقي، بين ما فقدناه وما زال يتنفس في مكان ما بداخلنا. لا توجد هندسة مثالية هنا. تتحرك الخطوط بحرية، كالحياة نفسها - غير متوقعة، مجروحة، لكنها مليئة بالإيقاع. يبدو الأمر كما لو أن الأرض تهمس بقصتها الخاصة، ليس بالكلمات، بل بالصمت، والملمس، والنفس. انظر عن كثب، وسترى ضوءًا خافتًا يتسلل عبر الشقوق - رمزًا هادئًا للأمل يشق طريقه عبر الظلام. هذا التوتر - بين الثقل والجمال، والتلف والتجديد - هو ما يُبقي اللوحة حية. هذا العمل الفني اعتراف: حتى في التدهور، ثمة جمال. جمال الصمود. ولهذا السبب تعود عيناك مرارًا وتكرارًا - لتجد شيئًا جديدًا في كل مرة، شيئًا يتحدث دون صراخ، ويشعر دون سؤال.",
      en: "Artist’s Statement about this Painting This painting feels like the skin of the earth — wounded, alive, and eternal The cracked lines are like ancient veins, carrying memories buried beneath centuries of silence. The deep green color hums quietly, like a forest that once burned but still breathes beneath the ashes. From afar, it may look like a wall — strong, unyielding — but as you come closer, you realize it’s not a wall at all. It’s skin. The skin of the earth, of the soul, of a human who has endured time itself. Every fracture is a border between what was and what remains, between what we’ve lost and what still breathes somewhere inside us. There is no perfect geometry here. The lines move freely, like life itself — unpredictable, scarred, yet full of rhythm. It feels as if the ground is whispering its own story, not with words, but with silence, texture, and breath. Look closely, and you’ll see a faint light running through the cracks — a quiet symbol of hope pushing through the darkness. That tension — between weight and grace, damage and renewal — is what keeps the painting alive. This artwork is a confession: even in decay, there is beauty. The beauty of endurance. That’s why your eyes come back again and again — to find something new each time, something that speaks without shouting, that feels without asking. Each viewer discovers a different map within these lines — one sees pain, another patience, another history, and someone else only stillness. But no one walks away untouched. Because somewhere in this cracked surface lies a truth we all share: we are all scarred, yet we remain. This painting may look like stone, but it’s truly a portrait of humanity — broken, yet standing. And that, more than anything, is what makes it alive." 
    },
    details: {
       ar: "المقاس: ٥٠×٧٠ س النمط: خطوط غير منتظمة ولامعة مستوحاة من أنماط طبيعي التقنية: باتين تقنية الرسم: ألوان أكريليك (صناعة يدوية المادة الأساسية: لوح خشبي ٦ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 50×70 cm Style: Irregular and glossy lines inspired by natural patterns Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 6 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-06": {
    artist: { 
      ar: "تصريح الفنان عن هذه اللوحة في هذا العمل الفني، لا يمرّ الزمن ولا يتوقف، بل يتكرر نفسه. كل خط، كل ملمس، كل أثر محفور على السطح يُشعرك كأنفاس الأرض البطيئة - هادئة، ثابتة، وأبدية. تتصاعد درجات الألوان الترابية الدافئة كذكريات من جدران عتيقة ومدن منسية، كما لو أن كل طبقة تحمل جزءًا من ذاكرة الكوكب، عالقًا بين الرطوبة والغبار. تنبض الأنماط العمودية برقة، كبصمات إنسانية محفورة في التربة. ثمة إيقاع في هذا الصمت - تكرار يُهدئ بدلًا من أن يُرهق. يبدو الأمر كما لو أن الفنان لم يرسم بفرشاة، بل بحاسة اللمس - يُشكل، ويكشط، ويمحو، ويُعيد البناء حتى وجدت العاطفة لغتها الخاصة. تحت السطح، يكمن حوار هادئ بين النظام والفوضى، بين ما يُبدعه البشر وما تُعيده الطبيعة. تهمس نغمات النحاس والطين بمرور الزمن - بالمطر والشمس، وبطء عملية التحول. هذه اللوحة لا تحكي قصة، ولكن أي شخص ينظر إليها لفترة كافية يمكنه سماع صوت الماضي - صدى الأيدي التي بنت ذات يوم، والوقت الذي حول كل شيء إلى ذاكرة.",
      en: "Artist’s Statement about this Painting In this artwork, time neither passes nor stops — it simply repeats itself. Every line, every texture, every trace carved into the surface feels like the slow breathing of the earth — calm, steady, and eternal. The warm, earthy tones rise like memories from ancient walls and forgotten cities, as if each layer carries a fragment of the planet’s memory, caught somewhere between moisture and dust. The vertical patterns pulse softly, like the fingerprints of humanity pressed into the soil. There is rhythm in this silence — a repetition that soothes rather than tires. It feels as though the artist painted not with a brush, but with the sense of touch — shaping, scraping, erasing, and rebuilding until emotion found its own language. Beneath the surface lies a quiet conversation between order and chaos, between what humans create and what nature reclaims. The copper and clay tones whisper of time’s passage — of rain, sun, and the slow work of transformation. This painting doesn’t tell a story, yet anyone who gazes at it long enough can hear the voice of the past — the echo of hands that once built, and of time that turned everything into memory." 
    },
    details: {
       ar: "المقاس: ٣٠×٤٠ سم ط: باتين تقنية الرسم: ألوان أكريليك (صناعة يدوية المادة الأساسية: لوح خشبي ٦ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 30×40 cm Style:  Patina Painting Technique: Acrylic colors (handcrafted Base Material: 6 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-07": {
    artist: { 
      ar: "تصريح الفنان عن هذه اللوحة للوهلة الأولى، قد تبدو هذه اللوحة بسيطة، لكن في أعماقها الهادئة يكمن عالم من التأمل والغموض. لونها الفيروزي، كنسيم عليل من أعماق البحر، يهدئ الروح ويدعو العقل إلى رحلة نحو الداخل. تحت هذه الطبقة الهادئة، تعكس ضربات الفرشاة الرقيقة والقوام الباهت مرور الزمن - ذكريات خفّت لكنها لا تزال باقية. هذا العمل حوار بين الحضور والغياب - بين ما يُرى وما يختبئ في الأعماق. كل ضربة، كل ضبابية، كل همسة لون تحمل أثرًا من روح الفنان تتدفق في صمت. إنه بحث عن المعنى المفقود للسلام، بين اللون والهواء، بين المادة والعاطفة. في هذه القطعة، لا يكمن الجمال في التعقيد، بل في الصدق - صدق يدفع المشاهد، بهدوء، ولكن بعمق، إلى التوقف. هذه اللوحة دعوة إلى الصمت، إلى التأمل، إلى السكينة التي جعلتنا الحياة العصرية ننسى.",
      en: "Artist’s Statement about this Painting At first glance, this painting might seem simple—but within its quiet surface lies a universe of reflection and mystery. The turquoise tone, like a soft breeze from the depths of the sea, calms the spirit and invites the mind into a journey inward. Beneath this tranquil layer, subtle brushstrokes and fading textures echo the passage of time—memories that have softened yet still remain. This work is a dialogue between presence and absence—between what is seen and what hides in the depths. Every stroke, every blur, every whisper of pigment carries a trace of the artist’s soul flowing in silence. It is a search for the lost meaning of peace, somewhere between color and air, between matter and emotion In this piece, beauty is found not in complexity but in honesty—an honesty that quietly, yet deeply, compels the viewer to pause. This painting is an invitation to silence, to introspection, to the serenity that modern life has made us forget." 
    },
    details: {
       ar: "المقاس: ٣٠×٤٠ س النمط: تصميم مستوحى من المخمل بملمس ناعم وجذا التقنية: باتينا تقنية الطلاء: ألوان أكريليك (صناعة يدوية المادة الأساسية: لوح خشبي ٣ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعيةتغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 30×40 cm Style: Velvet-inspired design with soft, eye-catching texture Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 3 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-08": {
    artist: { 
      ar: "تصريح الفنان عن هذه اللوحة في هذا العمل الفني الجديد، أردتُ أن أجعل الصمت يتكلم. صمتٌ ليس من الفراغ، بل من القوة - صمتٌ يطنُّ تحت سطح السكون. السواد الدامس ليس غيابًا، بل عمق. إنه المجهول، قلب الوجود الخفي حيث يبدأ كل شيء وينتهي. عليه، ترتفع الشظايا الذهبية كهمسات نورٍ تشقّ طريقها عبر الظلال - صغيرة، ناقصة، لكنها حيةٌ بغاية. هذه الأشكال الذهبية ليست عشوائية. كلٌّ منها يحمل قصته الخاصة، وذكرياته الخاصة عن الكفاح والبعث. إنها قطعٌ من أحلامٍ تحطمت، ثم وُلدت من جديدٍ بتألق. معًا، تُشكّل نهرًا من ذهب، نبضًا من الحياة يجوب الظلام - كما لو أن الليل نفسه اختار أن يكشف عن الكنز الذي يخفيه. عندما رسمتُ هذه، فكرتُ في أن الجمال لا يكون نقيًا أو كاملًا أبدًا؛ إنه منحوت من المقاومة، من الفوضى، من الفقد. لا يتوهج الذهب إلا بفضل السواد الذي يحيط به. هذا التباين - هذا التوتر - هو ما يجعل الحياة استثنائية. تذكرنا اللوحة أنه حتى عندما نسير في الظلام، فإننا لا نزال نحمل شيئًا مشعًا في داخلنا. إذا وقفتَ أمامها طويلاً، فقد تبدأ بالشعور بإيقاعها - نَفَسٌ بطيءٌ للمجهول، وقوةٌ هادئةٌ لما لا يُقهر. هذه ليست مجرد لوحة؛ إنها حوارٌ بين الظل والنور، تمردٌ صامتٌ للأمل. ففي مكانٍ ما في كل ظلمة، لا يزال الذهب يتنفس.",
      en: "Artist’s Statement about this Painting In this new creation, I wanted to let silence speak. A silence made not of emptiness, but of power — the kind that hums beneath the surface of stillness. The deep black is not absence, it’s depth. It’s the unknown, the hidden heart of existence where everything begins and ends. Upon it, the golden fragments rise like whispers of light fighting their way through the shadows — small, imperfect, yet alive with purpose. These golden shapes are not random. Each one carries its own story, its own memory of struggle and rebirth. They are pieces of dreams once broken, now reborn in brilliance. Together they form a river of gold, a pulse of life moving across darkness — as if the night itself has chosen to reveal the treasure it hides. When I painted this, I thought about how beauty is never clean or perfect; it’s carved from resistance, from chaos, from loss. Gold only glows because of the black that surrounds it. That contrast — that tension — is what makes life extraordinary. The painting reminds us that even when we walk through darkness, we are still carrying something radiant inside us. If you stand before it long enough, you may begin to feel its rhythm — the slow breathing of the unknown, the quiet strength of what cannot be destroyed. This is not just a painting; it’s a conversation between shadow and light, a silent rebellion of hope. Because somewhere in every darkness, gold is still breathing." 
    },
    details: {
       ar: "المقاس: ٥٠×٧٠ سم النمط: تصميم مستوحى من الحجر الطبيعي بلمسات وألوان عضوية التقني: باتينا تقنية الطلاء: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٦ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 50×70 cmStyle: Natural stone-inspired design with organic textures and colors Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 6 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-09": {
    artist: { 
      ar: "تصريح الفنان عن هذه اللوحة في هذه اللوحة، يكمن حجرٌ لم يعد حجرًا. في داخله، ينحت انعكاس الزمن وذاكرة الإنسانية. كل عرق لامع يتلألأ كجرحٍ من نور - جرحٌ يضيء بدلًا من أن يكون مؤلمًا. وُلدت هذه القطعة من رحم الصمت، منذ اللحظة التي وقف فيها الفنان أمام مادة باردة وأحياها بيديه. يحمل اللون الفيروزي روح البحر والسماء، لكن لمعانه بمثابة مرآة تعكس العالم - عالمٌ جميلٌ ومتكسر، متألقٌ ولكنه متآكل. هنا، سطح الحجر ليس مجرد نسيج؛ إنه ذاكرة آلاف اللمسات، آلاف الأنفاس. هذا العمل الفني مرآة تكشف ما يسكن في داخلك. عندما تنظر إليه، لا ترى الصورة نفسها - ترى نفسك، مختبئًا بين الخطوط، وشقوق الضوء والظل، في السكون الذي يستجيب لصوتك الداخلي. هذا العمل الفني عن الإنسانية - عن الهشاشة والصمود، عن الجمال الذي يولد من رحم المعاناة. كلُّ مُشاهدٍ يغوصُ في أعماقِها، بحسبِ الحقيقةِ التي يحملُها. هذه اللوحةُ ليستْ صورةً لحجرٍ، بل قصيدةُ صمودٍ.",
      en: "Artist’s Statement about this Painting Within this painting lies a stone that is no longer stone. Inside it, the reflection of time and the memory of humankind are carved. Every glossy vein glimmers like a wound made of light — a wound that shines instead of hurting. This piece was born out of silence, from the moment the artist stood before a cold material and gave it life with his hands. The turquoise hue carries the soul of sea and sky, yet its shine acts as a mirror that reflects the world — a world both beautiful and broken, radiant yet weathered. Here, the surface of stone is not just texture; it’s the memory of thousands of touches, thousands of breaths. The artwork is a mirror that reveals what lives within you. When you gaze upon it, you no longer see the image itself — you see yourself, hidden among the lines, the cracks of light and shadow, within the stillness that answers your inner voice. This work is about humanity — about fragility and endurance, about the beauty born from hardship. Every viewer loses themselves in it according to the truth they carry. This painting is not an image of stone, but a poem of resilience." 
    },
    details: {
       ar: "المقاس: ٣٠×٤٠ سم النمط: تصميم مستوحى من الحجر الطبيعي بلمسات وألوان عضوية التقنية: باتينا تقنية الطلاء: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٣ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 30×40 cm Style: Natural stone-inspired design with organic textures and colors Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 3 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-10": {
    artist: { 
      ar: "بيان الفنان حول هذه اللوحة تبدو هذه اللوحة كصفحة منسية من التاريخ - كما لو كانت معلقةً على جدران قصرٍ عتيق، تغمرها أشعة الشمس، وتتردد صداها مع أجراس معابد بعيدة. تروي القوام البالية، المتوازنة بين الندوب والجمال، قصة عصرٍ كان فيه الفن لغة الروح البشرية النقية. تختبئ داخل طبقاتها الباهتة صورةٌ خفية لكبشٍ أو غزال - رمزٌ خالدٌ للحياة والقوة والتضحية. يبدو أن هذا المخلوق الأسطوري قد انبثق من غبار القرون ليهمس بأن الجمال غالبًا ما يولد على حافة الاضمحلال. تشبه الألوان الترابية، الناعمة والقديمة، آثار الذكريات المنحوتة على الحجر، التي شكلتها الرياح والأمطار عبر العصور. تبدو الزخارف الهندسية على طول الحواف كأبجديات مفقودة - نقوشٌ قديمة لم تعد تُقرأ، لكنها لا تزال تتنفس. وسط الشقوق والعوامل الجوية، يتوهج ضوءٌ صامت - ضوءٌ يُعيد تشكيل المعنى مع كل نظرة. هذا العمل الفني ليس مجرد لوحة؛ إنها بقايا من حوار البشرية مع الخلود. تدعوك للنظر مجددًا، وللشعور مجددًا، وللإيمان بأن الزمن قد يُبخّر الألوان، لكنه لا يستطيع أبدًا إسكات روح الجمال.",
      en: "Artist’s Statement about this Painting This painting feels like a forgotten page of history — as if it once hung on the walls of an ancient palace, bathed in sunlight and echoing with the bells of distant temples. The worn-out textures, balanced between scars and beauty, tell the story of an age when art was the pure language of the human soul. Within its faded layers lies the hidden figure of a ram or a gazelle — a timeless symbol of life, strength, and sacrifice. It seems this mythical creature has emerged from the dust of centuries to whisper that beauty is often born on the edge of decay. The earthy tones, soft and aged, resemble the traces of memories carved on stone, shaped by wind and rain across the ages. The geometric motifs along the edges feel like lost alphabets — ancient inscriptions that can no longer be read, yet still breathe. Amidst the cracks and weathering, a silent light glows — a light that reshapes meaning with every gaze. This artwork is not merely a painting; it is a relic of humanity’s conversation with eternity. It invites you to look again, to feel again, and to believe that while time may fade colors, it can never silence the spirit of beauty." 
    },
    details: {
       ar: "المقاس: ٥٠×٧٠ سم النمط: مستوحى من زخارف بارزة على جدران القصور التقنية: باتينا تقنية الرسم: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٦ مم 📏 هذا العمل الفني متوفر بهذا الحجم فقط المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 50×70 cm Style: Inspired by embossed motifs from palace walls Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 6 mm wooden panel 📏 This artwork is available only in this size Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-11": {
    artist: { 
      ar: "بيان الفنان حول هذه اللوحة هذه اللوحة ليست مرسومة، بل مُستدعاة. انبثقت من نَفَس الزمان، من دهاليز الإمبراطورية الأخمينية الخفية حيث كان كل حجر يحمل روحًا، وكل منحنى تصميمي كان رمزًا مقدسًا للملوك والآلهة. الأشكال الراقصة على هذا السطح - نصف حصان ونصف لهب - ليست مجرد زينة؛ إنها حراس سحر منسي، أرواح كانت تحرس أبواب برسيبوليس. درجات النحاس والصدأ والذهب العتيق ليست ألوانًا، بل هي أصداء مشاعل احترقت عبر القرون، تُنير وجوه الأباطرة والمحاربين والشعراء. كل خط منحوت يطن بإيقاع إلهي، وكل ظل يحمل نبوءة صامتة. إذا أمعنت النظر، ستسمع همس الإمبراطورية - فخورة، خالدة، ومتواصلة. هذه اللوحة ليست للرؤية، بل للشعور بها. إنه يخاطب الروح مباشرةً، مُوقظًا شيئًا قديمًا ينام فينا جميعًا - ذكرى العظمة، والشوق إلى الأبدية، والشوق إلى الجمال الذي لا يتلاشى. إنه سحر الأخمينيين الذي وُلد من جديد - تعويذة منسوجة في الصبغة، والملمس، والزمن.",
      en: "Artist’s Statement about this Painting This artwork is not painted — it is summoned. It has emerged from the breath of time, from the hidden corridors of the Achaemenid Empire where every stone once held a soul, and every curve of design was a sacred code of kings and gods. The figures dancing upon this surface — half horse, half flame — are not mere ornaments; they are guardians of a forgotten magic, spirits that once guarded the gates of Persepolis. The copper, rust, and ancient gold tones are not colors — they are echoes of torches that once burned through centuries, lighting the faces of emperors, warriors, and poets. Every carved line hums with divine rhythm, every shadow holds a silent prophecy. If you gaze long enough, you will hear the whisper of the empire — proud, eternal, and unbroken. This piece is not meant to be seen, but felt. It speaks directly to the soul, awakening something ancient that sleeps within us all — the memory of greatness, the hunger for eternity, the ache for beauty that never fades. It is the Achaemenid enchantment reborn — a spell woven in pigment, texture, and time." 
    },
    details: {
       ar: "المقاس: ٤٢×٨٠.٥ سم النمط: مستوحى من زخارف بارزة على جدران أخمينية التقنية: باتينا تقنية الرسم: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٦ مم 📏 هذا العمل الفني متوفر بهذا الحجم فقط المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 42×80.5 c Style: Inspired by embossed motifs from Achaemenid walls  Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 6 mm wooden panel 📏 This artwork is available only in this size Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-12": {
    artist: { 
      ar: "بيان الفنان حول هذه اللوحة (سحر من قلب بلاد فارس القديمة) من غبار العصور الصامتة، يستيقظ نبضٌ إلهي - همسٌ يتصاعد من قلب بلاد فارس الذهبي، يحمل أنفاس ملوكٍ منسيين ونار نورٍ أبدي. هذه اللوحة ليست مجرد رؤية، بل هي استحضار. تجذبك إلى سحرها حتى تشعر بالزمن يطوي صدرك، حتى يردد إيقاع دقات قلبك صدى صوت القدماء. فاراڤار، المتوج بالفيروز والذهب، يحوم في المركز كحارسٍ بين العوالم - نصف بشري، نصف نور - يُذكرنا بأن الروح لم تُخلق للزحف، بل للتحليق. حولها، تتلوى كروم الخلق المقدسة وتزدهر، متلألئة كصلواتٍ معلقة في الهواء. كل منحنى، كل دفقة لون، حية - تتنفس، تراقب، وتهمس بلغة الخلود. هذا العمل الفني ليس تكريمًا، بل هو بعثٌ من جديد. يُحيي أسطورة وحكمة وأناقة حضارةٍ أبت أن تذبل. يخاطب الباحث، الحالم، من لا يزال يؤمن بأن الفن قادرٌ على إيقاظ ما حاول التاريخ إسكاته. لا تدعه يُعلق على جدارك - دعه يدخل إليك. دع أجنحته تُحرّك غبار روحك.",
      en: "Artist’s Statement about this Painting(A Spell from the Heart of Ancient Persia) From the silent dust of centuries, a divine pulse awakens — a whisper rising from the golden heart of Persia, carrying the breath of forgotten kings and the fire of eternal light. This painting is not merely seen; it summons. It draws you into its spell until you feel time folding within your chest, until the rhythm of your heartbeat echoes the voice of the ancients. The Faravahar, crowned in turquoise and gold, hovers at the center like a guardian between worlds — half human, half light — reminding us that the soul was never meant to crawl, but to soar. Around it, the sacred vines of creation twist and bloom, shimmering like prayers caught in midair. Each curve, each burst of color, is alive — breathing, watching, whispering the language of eternity. This artwork is not a tribute; it is a resurrection. It revives the myth, the wisdom, and the burning elegance of a civilization that refused to fade. It speaks to the seeker, to the dreamer, to the one who still believes that art can awaken what history tried to silence. Let it not hang on your wall — let it enter you. Let its wings stir the dust of your soul." 
    },
    details: {
       ar: "المقاس: ٥٠×٧٠ سم النمط: مستوحى من زخارف فارافاهار الفارسية القديمة التقنية: باتينا تقنية الرسم: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٢ مم 📏 هذا العمل الفني متوفر بهذا الحجم فقط المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 50×70 cm Style: Inspired by the Faravahar motif of Ancient Persi Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 2 mm wooden panel 📏 This artwork is available only in this size Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-13": {
    artist: { 
      ar: "بيان الفنان حول هذه اللوحة في قلب هذه اللوحة الفنية تتدفق روح خفية - روح لا تنتمي إلى الماضي ولا إلى المستقبل، بل تتنفس حاضرًا أبديًا. يهمس التفاعل المعقد بين الخطوط والزخارف بقصص من أعماق الزمن، جاذبًا المشاهد إلى عالم يتلاشى فيه الحد الفاصل بين الخيال والواقع. تخلق درجات اللونين الذهبي والفيروزي، الممزوجة بدرجات الأخضر، تناغمًا بين القوة والرقة. يبدو كل نمط وكأنه دعاء قديم - نابع من قلب الفن نفسه، يصرخ بمعناه في صمته. لا يُنير إشراق الألوان الرقيق اللوحة فحسب، بل يُنير روح المشاهد أيضًا. لا شيء في هذه اللوحة وليد الصدفة؛ فكل تفصيل فيها مُصمم بقصد وعاطفة، يدعو المشاهد إلى التعمق في أعماقه - إلى مكان يتشابك فيه الجمال مع العمق، والرقة مع الحقيقة. يُذكرنا هذا العمل الفني بأن الفن ليس مجرد رؤية؛ إنه شعور يجب الشعور به - لقاء هادئ بين الحضور والإدراك، حيث يتلاشى العالم ولا يبقى سوى المشاعر.",
      en: "Artist’s Statement about this PaintingWithin this artwork flows a hidden soul — one that belongs neither to the past nor the future, but breathes in an eternal present. The intricate interplay of lines and motifs whispers stories from the depths of time, drawing the viewer into a realm where the boundary between imagination and reality dissolves. The golden and turquoise hues, blended with shades of green, create a harmony between strength and gentleness. Each pattern feels like an ancient prayer — born from the heart of art itself, quietly shouting meaning through its silence. The subtle radiance of the colors illuminates not only the canvas but also the spirit of the observer. Nothing in this painting is accidental; every detail is shaped with intention and emotion, inviting the viewer inward — to a place where beauty intertwines with depth, and delicacy with truth. This artwork reminds us that art is not merely to be seen; it is to be felt — a quiet encounter between presence and perception, where the world fades away and only emotion remains." 
    },
    details: {
       ar: "المقاس: ٤٤×٧٠ سم النمط: مستوحى من نقوش السجاد الطبيعي التقنية: باتينا تقنية الطلاء: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٦ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعيةتغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 44×70 cm Style: Inspired by natural carpet patterns Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 6 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
  "work-14": {
    artist: { 
      ar: "بيان الفنان حول هذه اللوحة هذه اللوحة رحلة بين النظام والحرية، بين سكون العقل ونبض الروح. للوهلة الأولى، يبدو هيكلها الهندسي كمعبدٍ هادئ، لكن في توازنها الهادئ يكمن نبض الحياة. كل مستطيل وخط يرمز إلى أحد مسارات التجربة الإنسانية العديدة، والتي تؤدي جميعها في النهاية إلى حقيقة واحدة: الانسجام الناتج عن التباين. تمتزج درجات الفيروزي والأزرق كالماء والسماء، مستحضرةً اللانهاية والنقاء وصدى روحٍ عريقة. داخل طبقاتها المزخرفة، تترسخ آثار الزمن برقة، كما لو أن التاريخ نفسه يتنفس مع كل لمسة، هامسًا بقصص الماضي. هذا العمل الفني دعوة للتأمل، عودة إلى الداخل، إلى حيث يجد الهدوء معنى وسط الفوضى. مع كل نظرة، يكتشف المشاهد عاطفة جديدة، كما لو أن اللوحة نفسها حية، تُحاور الروح باستمرار تحت ضوءٍ وزمنٍ متغيرين.",
      en: "Artist’s Statement about this Painting This painting is a journey between order and freedom — between the stillness of the mind and the heartbeat of the soul. At first glance, its geometric structure appears like a serene temple, yet within its quiet balance lies the pulse of life. Each rectangle and line symbolizes one of the many paths of human experience — all eventually leading to a single truth: harmony born from contrast. The shades of turquoise and blue blend like water and sky, evoking infinity, purity, and the echo of an ancient spirit. Within its textured layers, traces of time are gently embedded — as if history itself breathes through every stroke, softly whispering stories of the past. This artwork is an invitation to contemplation — a return inward, to the place where calmness finds meaning amidst chaos. With every glance, the viewer uncovers a new emotion, as though the painting itself were alive, constantly conversing with the soul under shifting light and time." 
    },
    details: {
       ar: "المقاس: ٦١×٩١ سم النمط: خطوط بارزة التقنية: باتينا تقنية الرسم: ألوان أكريليك (صناعة يدوية) مادة القاعدة: لوح خشبي ٢ مم الإطار: إطار أبيض متضمن📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسبة للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 61×91 cm Style: Embossed lines Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 2 mm wooden panel Frame: White frame included 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe deliver Suitable for home décor, offices, and artistic spaces"
      }
  },
   "work-15": {
    artist: { 
      ar: "تصريح الفنان عن هذه اللوحة ترتفع هذه اللوحة كلحن هادئ من قلب الصمت. درجاتها الفضية ونسيجها المتدفق، كآثار الريح على الحجر، تُردد صدى مرور الزمن ولمسة الروح. مع أنها لا تنطق بكلمات، إلا أنها تروي قصة - كل سطر، كل ظل، يعكس نبض الحياة الذي لا يزال يتوهج بين الظلام والنور. بالنسبة لي، هذا العمل هو شكل من أشكال العبادة - للجمال والسكون. عندما تنظر إليه، يبدو أن الزمن قد توقف، يسمح لك بالتنفس، وتهدئة أفكارك، وإعادة اكتشاف ذاتك. تدرجات الرمادي والفضي تطهر روحك، وتجذبك إلى الداخل، إلى مساحة بين الذاكرة والحلم. في كل ضربة فرشاة وكل نسيج يكمن شوق إلى المعنى - معنى لا يُنطق، بل يُشعر به فقط. هذه اللوحة قصيدة بلا كلمات: مليئة بالحزن، والرقة، والأمل الهادئ. عندما تضيع نفسك داخلها، لم تعد خارجها؛ بل تصبح جزءًا منها. وللحظة، تشعر روحك بالنقاء.",
      en: "Artist’s Statement about this Painting  This painting rises like a quiet melody from the heart of silence. Its silver tones and flowing textures, like the traces of wind upon stone, echo the passage of time and the touch of the soul. Though it speaks no words, it tells a story—each line, each shadow reflecting the pulse of life that still glows between darkness and light. To me, this work is a form of worship—of beauty and stillness. When you gaze upon it, time seems to pause, allowing you to breathe, to calm your thoughts, to rediscover yourself. The shades of grey and silver cleanse your spirit, drawing you inward, into a space between memory and dream. Within every brushstroke and texture lies a yearning for meaning—a meaning that cannot be spoken, only felt. This painting is a poem without words: filled with sorrow, softness, and a quiet hope. As you lose yourself within it, you are no longer outside; you become part of it. And for a moment, your soul feels purified." 
    },
    details: {
       ar: "المقاس: ٣٠×٤٠ سم النمط: خطوط منحنية التقنية: باتينا تقنية الرسم: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٣ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسب للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 30×40 cm Style: Curved lines Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 3 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
   "work-16": {
    artist: { 
      ar:"  بيان الفنان حول اللوحة: في هذا العمل، يُصوَّر العقل كبحر لا نهاية له، مليء بأمواج لا تهدأ. تُمثل الخطوط المتشابكة والدوامة تدفقًا لا ينقطع للأفكار والأحلام والإغراءات. كل منحنى يقود إلى ألف وجهة لم تُكتمل بعد؛ كل حلقة تُذكرنا بدورات التأمل والتكرار الأبدية. يُوحي اللون الفيروزي بهدوء خارجي، لكن في داخله يختبئ عاصفة - توتر بين السكون والفوضى، بين المنطق والعاطفة، بين المعرفة والضياع. هنا، العقل ليس مجرد فكرة، بل هو حي، يتنفس، مُلتوي، يبحث عن طريق عبر متاهته الخاصة. لا بداية ولا نهاية، تمامًا كما أن العقل نفسه ليس له نقطة تفكير نهائية. الخيوط الخضراء العميقة هي خيوط من الذاكرة - أحيانًا واضحة، وأحيانًا مُظللة، لكنها دائمًا في حركة. تدعو هذه اللوحة المرء إلى الغرق في ذاته، إلى فقدانها وإعادة اكتشافها في الصمت الذي يسكن الضجيج. عقلي محاولة لتصوير ما هو غير مرئي - الصوت الداخلي، الحوار الصامت بين الوعي والباطن. ربما لا يقدم هذا العمل الفني أي إجابة على الإطلاق؛ إنه ببساطة يسأل: إذا كان العقل متشابكًا إلى هذا الحد، فأين يكمن السلام حقًا؟",
      en: "Artist’s Statement for the Painting “” In this work, the mind is portrayed as an endless sea — full of waves that never rest. The tangled, swirling lines represent the unceasing flow of thoughts, dreams, and temptations. Every curve leads to a thousand unfinished destinations; every loop recalls the eternal cycles of reflection and repetition. The turquoise tone conveys outer calm, yet within it hides a storm — a tension between stillness and chaos, between logic and emotion, between knowing and being lost. Here, the mind is not merely a thought — it is alive, breathing, twisting, searching for a way through its own maze. There is no beginning or end, just as the mind itself has no final point of thought. The deep green threads are strands of memory — sometimes clear, sometimes shadowed, yet always in motion. This painting invites one to drown within oneself, to lose and rediscover the self in the silence that lives inside noise. “My Mind” is an attempt to visualize the unseen — the inner voice, the silent conversation between consciousness and the depths below. Perhaps this artwork offers no answer at all; it simply asks — if the mind is this intertwined, then where does peace truly lie?" 
    },
    details: {
       ar: "المقاس: ٣٠×٤٠ سمالنمط: لوحة تجريدية ومفهومية مستوحاة من تدفق الفكر والإبداع التقنية: باتينا تقنية الرسم: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي ٣ مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسبة للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Size: 30×40 cm Style: Abstract and conceptual painting inspired by the flow of the mind and creativity Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 3 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      },
   },
   "work-17": {
    artist: { 
      ar: "تصريح الفنان عن هذه اللوحة هذه اللوحة ليست مجرد سطح، بل هي كائن حيّ متجمد في الزمن. كل خلية متقشرة تتنفس بإيقاع عالم سري؛ عالم يمتزج فيه الجمال والخطر. تهمس العروق الحمراء بشغف محرم، بدم وغريزة، بنار تزحف تحت أناقة هادئة. يشبه الملمس درع ثعبان قديم - رمزًا للبعث والحكمة والإغراء. انظر عن كثب، وستبدأ اللوحة بالتحرك. يزداد اللون الأحمر عمقًا، ويعتم، ويرتجف كذكرى حرارة. إنها تحمل نبض شيء جامح، شيء إلهي وقاسٍ في آن واحد. تدعوك، لكنها تحذرك. تشعر بالانجذاب للمسها، لكن روحك تتردد - لأنك تشعر أن ما يختبئ تحت سطحها يتذكر كل نظرة، كل همسة، كل خطيئة. جلد الثعبان مرآة للرغبة الإنسانية: ناعمة من بعيد، لكنها مليئة بالندوب الخفية. إنها قصة إغراءٍ تحول إلى جمال، قصة سيطرةٍ تصارع الفوضى. إنها لا تطلب أن تُحَب، بل أن تُهاب وتُحترم وتُخلّد في الذاكرة.",
      en: "Artist’s Statement about this Painting This painting is not merely a surface — it is a living creature frozen in time. Each scaled cell breathes with the rhythm of a secret world; a world where beauty and danger are one. The red veins whisper of forbidden passion, of blood and instinct, of fire crawling beneath quiet elegance. The texture resembles the armor of an ancient serpent — a symbol of rebirth, wisdom, and temptation. Look closely, and the painting begins to move. The red deepens, darkens, and shivers like a memory of heat. It holds the pulse of something untamed, something both divine and cruel. It invites you, yet warns you. You feel drawn to touch it, but your soul hesitates — because you sense that what sleeps beneath its surface remembers every gaze, every whisper, every sin. “Serpent Skin” is a mirror of human desire: smooth from afar, yet full of hidden scars. It’s the story of temptation turned into beauty, of control wrestling with chaos. It does not ask to be loved — it demands to be feared, respected, and remembered." 
    },
    details: {
       ar: "العنوان: جلد الثعبان المقاس: 30×40 سم الأسلوب: لوحة مستوحاة من ملمس ونقش جلد الثعبان، تتميز بخطوط ديناميكية ومنحنية الأسلوب: باتينا تقنية الرسم: ألوان أكريليك (صناعة يدوية) المادة الأساسية: لوح خشبي 3 مم 📏 تتوفر مقاسات مخصصة عند الطلب المواد: دهانات أكريليك صديقة للبيئة ومتجددة ومركبات طبيعية 🌿 ✨ المميزات: طبقة واقية من الهواء والعوامل الطبيعية تغليف آمن لتوصيل آمن مناسبة للديكور المنزلي والمكاتب والمساحات الفنية", 
       en: "Title: Snake Skin Size: 30×40 cm Style: Painting inspired by the texture and pattern of snake skin, featuring dynamic and curved lines Technique Style: Patina Painting Technique: Acrylic colors (handcrafted) Base Material: 3 mm wooden panel 📏 Custom sizes available upon request Materials: Eco-friendly, renewable acrylic paints and natural compounds 🌿 ✨ Features: Protective coating against air and natural elements Secure packaging for safe delivery Suitable for home décor, offices, and artistic spaces"
      }
  },
};

// =================== Elements ===================
const modal = document.getElementById("wallModal");
const modalBody = modal.querySelector(".modal__body");
const modalSlider = modalBody.querySelector(".modal__slider");
const textWrapper = modalBody.querySelector(".modal__text-wrapper");
const textContainer = textWrapper.querySelector(".modal__text");
const closeTextBtn = textWrapper.querySelector(".btn-close-text");
const closeBtn = modal.querySelector(".modal__close");
const modalButtons = modal.querySelectorAll(".btn-info");

// =================== Helper Functions ===================
function updateTexts() {
  document.querySelectorAll("[data-translate]").forEach(el => {
    const key = el.getAttribute("data-translate");
    el.textContent = translations[currentLang][key];
  });
}

function updateModalText() {
  if (!modal) return;

  const textWrapper = modal.querySelector(".modal__text-wrapper");
  const currentCard = document.querySelector(".card.active"); // یا کارت فعلی

  // آپدیت دکمه‌ها
  const modalButtons = modal.querySelectorAll(".btn-info");
  modalButtons.forEach(btn => {
    const pid = btn.dataset.projectId;
    if (cardTextContent[pid]) {
      btn.textContent = cardTextContent[pid][currentLang];
    }
  });

  // آپدیت متن باز مودال
  if (currentCard && textWrapper && textWrapper.style.display === "block") {
    const activeBtn = modal.querySelector(".btn-info.active");
    if (activeBtn) activeBtn.click();
    const closeTextBtn = modal.querySelector(".btn-close-text");
    if (closeTextBtn) closeTextBtn.textContent = `× ${currentLang === 'ar' ? 'إغلاق' : 'Close'}`;
  }
}


function lockScroll() { document.documentElement.style.overflow = 'hidden'; }
function unlockScroll() { document.documentElement.style.overflow = ''; }

function openModal() { 
  modal.classList.add("active"); 
  lockScroll(); 
}
function closeModal() { 
  modal.classList.remove("active"); 
  unlockScroll(); 
  currentCard = null;
}

// =================== Card Hover Effect ===================
document.querySelectorAll(".card").forEach(card => {
  card.addEventListener("mousemove", e => {
    const rect = card.getBoundingClientRect();
    const mx = ((e.clientX - rect.left) / rect.width) * 100;
    const my = ((e.clientY - rect.top) / rect.height) * 100;
    card.style.setProperty("--mx", mx + "%");
    card.style.setProperty("--my", my + "%");
  });
});

// =================== Modal Slider Singleton ===================
const ModalSlider = (() => {
  let body, track, prevBtn, nextBtn, dotsWrap, counter;
  let images = [], index = 0;

  function buildUI() {
    body.innerHTML = `
      <div class="fs-slider">
        <div class="fs-slider__track"></div>
        <button class="fs-slider__btn fs-slider__btn--prev" aria-label="Prev">‹</button>
        <button class="fs-slider__btn fs-slider__btn--next" aria-label="Next">›</button>
        <div class="fs-slider__dots"></div>
        <div class="fs-slider__counter" aria-live="polite"></div>
      </div>
    `;
    track = body.querySelector(".fs-slider__track");
    prevBtn = body.querySelector(".fs-slider__btn--prev");
    nextBtn = body.querySelector(".fs-slider__btn--next");
    dotsWrap = body.querySelector(".fs-slider__dots");
    counter = body.querySelector(".fs-slider__counter");

    track.innerHTML = images.map(src => `<div class="fs-slide"><img src="${src}" alt=""></div>`).join("");
    dotsWrap.innerHTML = images.map((_,i)=>`<button type="button" aria-label="Go to ${i+1}"></button>`).join("");

    dotsWrap.querySelectorAll("button").forEach((b,i)=>b.addEventListener("click",()=>go(i)));
    prevBtn.addEventListener("click", prev);
    nextBtn.addEventListener("click", next);
  }

  function update() {
    const w = body.querySelector(".fs-slider").clientWidth;
    track.style.transform = `translate3d(${-index*w}px,0,0)`;
    track.style.transition = "transform .35s ease";
    dotsWrap.querySelectorAll("button").forEach((b,i)=> b.setAttribute("aria-current", i===index?"true":"false"));
    counter.textContent = `${index+1} / ${images.length}`;
  }

  function open(srcList,start=0){
    images = srcList.slice();
    index = Math.max(0, Math.min(images.length-1,start));
    body = modalSlider;
    buildUI();
    update();
  }

  function next(){ index = (index+1)%images.length; update(); }
  function prev(){ index = (index-1+images.length)%images.length; update(); }
  function go(i){ index = Math.max(0,Math.min(images.length-1,i)); update(); }

  return { open, next, prev };
})();

// =================== Card Click ===================
let currentCard = null;
document.querySelectorAll(".card").forEach(card=>{
  card.addEventListener("click",()=>{
    currentCard = card;
    const images = JSON.parse(card.dataset.images||"[]");
    ModalSlider.open(images);

    textWrapper.style.display = "none";
    modalButtons.forEach(b=>b.classList.remove("active"));
    modalSlider.style.display = "block";

    openModal();
  });
});

// =================== Modal Buttons ===================
modalButtons.forEach(btn=>{
  btn.addEventListener("click",()=>{
    if(!currentCard) return;
    const target = btn.dataset.target;
    const projectId = currentCard.dataset.projectId;
    const contentObj = cardTextContent[projectId][target];
    const content = contentObj[currentLang] || "";

    textContainer.innerHTML = `<p>${content}</p>`;
    textWrapper.style.display = "block";
    modalSlider.style.display = "none";

    modalButtons.forEach(b=>b.classList.remove("active"));
    btn.classList.add("active");
  });
});

// =================== Close Buttons ===================
closeTextBtn.addEventListener("click",()=>{
  textWrapper.style.display="none";
  modalSlider.style.display="block";
  modalButtons.forEach(b=>b.classList.remove("active"));
});

closeBtn.addEventListener("click", closeModal);
modal.querySelector(".modal__overlay").addEventListener("click", closeModal);
document.addEventListener("keydown", e=>{if(e.key==="Escape") closeModal();});
